### PR TITLE
add toolbar

### PR DESCRIPTION
**Pull request by 74ls00**
The toolbar requires PIL.

Linux.

pip uninstall pillow

sudo apt-get install libjpeg62-dev zlib1g-dev libfreetype6-dev liblcms1-dev python-dev

pip install pillow

It may be necessary

sudo apt-get install python-setuptools

http://python.su/forum/topic/31899/?page=1

Windows.

Install Pillow-4.0.0.win32

https://pypi.python.org/pypi/Pillow/4.0.0

### CODE REVIEW

**Comment by dhowland** [comment]
Okay two things:

1) You don't need to re-import tk and ttk, they are already imported.
2) Why not just use .gif icons?  that way we don't need to add a dependency for PIL, which complicates the install.

**Comment by 74ls00** [comment]
I know English bad. We have very little documentation about Python.
I made changes for a long time, in part I already forgot what's what.

1. I suggested the option that I earned.
`Import tkinter.ttk as ttk` 
this line is probably superfluous. I forgot why she added it.
Now there is no way to test for Linux, maybe it's for him.

2. Perhaps you can simplify this so that you do not use PIL.

**Comment by dhowland** [comment]
I cleaned it up a bit.  If there will be an icon bar, I think tooltips are needed.  It isn't obvious what each icon does.

**Comment by dhowland** [comment]
I added tooltips.  Please add copy/paste icons.  And, perhaps one for LED assignment.

**Comment by 74ls00** [comment]
2c6904c
In this form does not work with Python 2.7

The badges have become buttons, it's not aesthetically pleasing.

6f0b55f
Does not work. Probably there are no necessary libraries.

>    File "EasyAVR \ keymapper \ easykeymap \ gui.py ", line 39, in <module>
>      From idlelib.ToolTip import ToolTip
> ModuleNotFoundError: No module named 'idlelib.ToolTip'

In my version, there was more stability. I think there you can add tips.

**Comment by dhowland** [comment]
You're right.  My updates only work on Python 3.

**Comment by dhowland** [comment]
The old 2.x GUI has been completely replaced, obsoleting this request.

**Pull request closed without merging**
