### PR TITLE
added TADA68 support

### PR DESCRIPTION
**Pull request by hillam**

### CODE REVIEW

**Comment by hillam** [comment]
I think I just figured out that this does not work.. Please give me a bit of time to see about fixing it.

**Comment by dhowland** [comment]
Oops.  Based on the earlier emails, I figured it was tested.  What's wrong with it?

**Comment by hillam** [comment]
I feel extremely silly, and I'm working to get it sorted out now. If you recall, I recounted "getting it working" with Terry's suggestions, and then not seeing any difference in changing the PULLUP/PULLDOWN backlight setting. I think what actually happened was: the way I was flashing the firmware wasn't overriding what was on the board, so "getting it working" was actually not overriding my almost identically laid out exiting firmware, and "not seeing any difference" in those settings was the result of me changing them, not successfully flashing, and seeing no change in behavior. 

I'm horribly sorry, and especially sorry that I didn't confirm this prior to making this pull request. I'll work to get it fixed, get another user to confirm, and get back to you.

**Comment by dhowland** [comment]
Yeah don't worry about it, no harm done.  If you need help just let me know.

**Comment by hillam** [comment]
### Good news: 
Turns out my code does, in fact work! 🎈 🎉 🎂 

### Bad news: 
I bricked my TADA68, and had to fall back onto using a DFU bootloader with some guidance from @TerryMathews. This means I loaded my firmware via the .hex output of EasyAVR outside of the standard TADA68 mass storage bootloader programming method and therefore I can't verify that it actually works with that method. 

---
I did, however find that my CAPS LED setting was inverted. Shall I make another pull request just for that feature?

**Comment by dhowland** [comment]
Why don't you let me take a crack at it?  I'll commit it now...

**Comment by hillam** [comment]
Have at it. Thanks. Sorry for that.

**Comment by dhowland** [comment]
Okay, I fixed up some of the whitespace, reversed the Caps Lock LED, and corrected the number of indicators.

**Pull request merged**
